import goodCat from "../assets/imgs/white_kitten.jpg"
import badCat from "../assets/imgs/bad_kitten.jpg"
import goodDog from "../assets/imgs/black_labrador.jpg"
import badDog from "../assets/imgs/white_pom.jpg"

let petInfo = [
  {
    title: "Good Cat of the Month",
    id: 1,
    name: "Soju",
    species: "Cat",
    color: "White",
    age: "3 months",
    gender: "Boy",
    pic: goodCat,
  },
  {
    title: "Bad Cat of the Month",
    id: 2,
    name: "Zoe",
    species: "Cat",
    color: "Black",
    age: "4 months",
    gender: "Girl",
    pic: badCat,
  },
  {
    title: "Good Dog of the Month",
    name: "Jack",
    id: 3,
    species: "Dog",
    color: "Black",
    age: "7 months",
    gender: "Boy",
    pic: goodDog,
  },
  {
    title: "Bad Dog of the Month",
    name: "Joy",
    id: 4,
    species: "Dog",
    color: "White",
    age: "10 months",
    gender: "Boy",
    pic: badDog,
  },
  {
    title: "Good Cat of the Month",
    name: "Soju",
    id: 5,
    species: "Cat",
    color: "White",
    age: "3 months",
    gender: "Boy",
    pic: goodCat,
  },
  {
    title: "Bad Cat of the Month",
    name: "Zoe",
    id: 6,
    species: "Cat",
    color: "Black",
    age: "4 months",
    gender: "Girl",
    pic: badCat,
  },
  {
    title: "Good Dog of the Month",
    name: "Jack",
    id: 7,
    species: "Dog",
    color: "Black",
    age: "7 months",
    gender: "Boy",
    pic: goodDog,
  },
  {
    title: "Bad Dog of the Month",
    name: "Joy",
    id: 8,
    species: "Dog",
    color: "White",
    age: "10 months",
    gender: "Boy",
    pic: badDog,
  },
  {
    title: "Good Cat of the Month",
    name: "Soju",
    id: 9,
    species: "Cat",
    color: "White",
    age: "3 months",
    gender: "Boy",
    pic: goodCat,
  },
  {
    title: "Bad Cat of the Month",
    name: "Zoe",
    id: 10,
    species: "Cat",
    color: "Black",
    age: "4 months",
    gender: "Girl",
    pic: badCat,
  },
  {
    title: "Good Dog of the Month",
    name: "Jack",
    id: 11,
    species: "Dog",
    color: "Black",
    age: "7 months",
    gender: "Boy",
    pic: goodDog,
  },
  {
    title: "Bad Dog of the Month",
    name: "Joy",
    id: 12,
    species: "Dog",
    color: "White",
    age: "10 months",
    gender: "Boy",
    pic: badDog,
  },
  {
    title: "Good Cat of the Month",
    name: "Soju",
    id: 13,
    species: "Cat",
    color: "White",
    age: "3 months",
    gender: "Boy",
    pic: goodCat,
  },
  {
    title: "Bad Cat of the Month",
    name: "Zoe",
    id: 14,
    species: "Cat",
    color: "Black",
    age: "4 months",
    gender: "Girl",
    pic: badCat,
  },
  {
    title: "Good Dog of the Month",
    name: "Jack",
    id: 15,
    species: "Dog",
    color: "Black",
    age: "7 months",
    gender: "Boy",
    pic: goodDog,
  },
  {
    title: "Bad Dog of the Month",
    name: "Joy",
    id: 16,
    species: "Dog",
    color: "White",
    age: "10 months",
    gender: "Boy",
    pic: badDog,
  },
  {
    title: "Good Cat of the Month",
    name: "Soju",
    id: 17,
    species: "Cat",
    color: "White",
    age: "3 months",
    gender: "Boy",
    pic: goodCat,
  },
]

export default petInfo;